Removing Allocation for Inexact Jacobian
SciML/NonlinearSolve.jl pull request #266
Opened 2023-10-27 21:37 UTC by yonatanwesen

This PR make sure that we don't allocate memory when computing the inexact Jacobian for PT methods. Instead, we just overwrite the jacobian that is already allocated.

2023-10-27 22:20 UTC, avik-pal requested changes

2023-10-27 22:20 UTC, avik-pal commented on src/pseudotransient.jl
> +    #J_new = J - (1 / alpha) * I
remove

2023-10-27 22:20 UTC, avik-pal commented on src/pseudotransient.jl
> +        cache.du = fu1 / (cache.J)
remove parenthesis

2023-10-28 03:29 UTC, ChrisRackauckas commented on src/pseudotransient.jl
> +        J .= J - (1 / alpha) * I
This still allocates. Use the same flow as https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/derivative_utils.jl#L494-L503

2023-10-31 20:20 UTC, avik-pal requested changes

2023-10-31 20:20 UTC, avik-pal commented on Project.toml
> +FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
Missing compat

2023-10-31 20:20 UTC, avik-pal commented on src/NonlinearSolve.jl
> +    using FastBroadcast: @.., True, False
`True` / `False` not used anywhere. Also they are defined by `Static.jl`, it is a bad practice to import types of a 3rd package via the 2nd

2023-10-31 20:20 UTC, avik-pal commented on src/pseudotransient.jl
>              b = _vec(fu1),
```suggestion
        linres = dolinsolve(alg.precs, linsolve; A = cache.J, b = _vec(fu1),
```

2023-11-01 06:02 UTC, ChrisRackauckas approved these changes

2023-11-01 06:03 UTC, merged